# Generated by Django 3.1.4 on 2020-12-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edYou', '0002_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.CharField(max_length=32),
        ),
    ]
