# Generated by Django 3.1.4 on 2020-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edYou', '0009_chapter_enrolled_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=16),
        ),
    ]
