# Generated by Django 3.1.3 on 2020-12-22 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edYou', '0012_auto_20201222_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='enroll',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='edYou.enrolled'),
        ),
    ]
