# Generated by Django 3.1.3 on 2020-12-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edYou', '0013_auto_20201222_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='num',
        ),
        migrations.RemoveField(
            model_name='video',
            name='num',
        ),
        migrations.AlterField(
            model_name='notes',
            name='enroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edYou.enrolled'),
        ),
    ]
