# Generated by Django 3.1.3 on 2020-12-27 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edYou', '0014_auto_20201227_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='enroll',
        ),
    ]
