# Generated by Django 3.1.3 on 2021-01-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edYou', '0015_remove_notes_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
